# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38dc598ea8461f5ab24a2eedebace0f4c3c5bdb33df777cf073cee11c59199e7f96510e3e8f40e109af13c03befa0313d6981908045a5fe41064400e131f2e0d

test:
  secret_key_base: 09fb9a1842e11a4b7ca2bafb785c5f62afc775ccaf2d43f50f4e865d6a7b936431abd770e50a4e85a1ba3824b88e198cabc3d039a6f4cf4df7f87979ac138fe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
